//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JegoDatabase.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remain
    {
        public string fh_code { get; set; }
        public string f_code { get; set; }
        public string date { get; set; }
        public decimal amount { get; set; }
        public string deadline { get; set; }
        public string deadline_date { get; set; }
        public decimal remain_amount { get; set; }
    }
}
